/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  DatePicker,
  Form,
  Input,
  message,
  Modal,
  Pagination,
  Select,
} from "antd";
import { FC, useRef, useState } from "react";
import setting from "../../assets/images/Settings.png";
import { HiOutlineArrowNarrowDown } from "react-icons/hi";
import {
  // useGetDepositStatsQuery,
  useGetMyBalanceQuery,
  useGetOrgAllDepositsQuery,
  usePayoutRequestMutation,
} from "../../redux/features/depositApi/depositApi";
import jsPDF from "jspdf";

const Deposits: FC = () => {
  const [page, setPage] = useState(1);
  const [limit] = useState(2);
  const [status] = useState("pending");
  const [payoutMethod, setPayoutMethod] = useState("stripe_connect");
  const [searchTerm] = useState("");
  const [sort] = useState("");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);

  const [form] = Form.useForm();
  // const { data: depositStats } = useGetDepositStatsQuery("");
  const { data: depositData } = useGetOrgAllDepositsQuery({
    status,
    payoutMethod,
    searchTerm,
    sort,
    page,
    limit,
  });
  console.log(depositData);
  const { data: getMyBalance } = useGetMyBalanceQuery("");
  const handleDownLoadPdf = (item: any) => {
    try {
      const pdf = new jsPDF("p", "mm", "a4");

      // HEADER BAR
      pdf.setFillColor(76, 90, 241);
      pdf.rect(0, 0, 210, 25, "F");
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(255);
      pdf.setFontSize(18);
      pdf.text("Deposit Receipt", 15, 17);

      // Content Box
      pdf.setDrawColor(200);
      pdf.roundedRect(10, 35, 190, 110, 5, 5);

      // Amount Big Heading
      pdf.setTextColor(30);
      pdf.setFontSize(28);
      pdf.text(
        `${item.requestedAmount ?? item.amount} ${item.currency ?? ""}`,
        20,
        60
      );

      pdf.setFontSize(11);
      pdf.setTextColor(100);
      pdf.text(
        `Transaction ID: $   ${
          item.organization?.stripeConnectAccountId
            ? item.organization?.stripeConnectAccountId.slice(0, 3) +
              "*".repeat(item.organization?.stripeConnectAccountId.length - 7) +
              item.organization?.stripeConnectAccountId.slice(-4)
            : ""
        } `,
        20,
        70
      );

      // LEFT INFO
      pdf.setTextColor(50);
      pdf.setFontSize(12);
      pdf.text("Deposited To", 20, 90);
      pdf.setFont("normal");
      pdf.text(item.organization?.name ?? "Not Provided", 20, 97);

      pdf.setFont("bold");
      pdf.text("Transfer Method", 20, 115);
      pdf.setFont("normal");
      pdf.text(item.payoutMethod ?? item.method ?? "Unknown", 20, 122);

      // STATUS BADGE
      const badgeColor =
        item.status === "Successful"
          ? [49, 196, 141]
          : item.status === "Pending"
          ? [250, 204, 21]
          : [239, 68, 68];

      pdf.setFillColor(...(badgeColor as [number, number, number]));

      pdf.roundedRect(130, 85, 60, 12, 3, 3, "F");
      pdf.setTextColor(255);
      pdf.text(item.status?.toUpperCase() ?? "UNKNOWN", 138, 93);

      // Timestamp
      pdf.setFontSize(12);
      pdf.setTextColor(30);
      pdf.text("Timestamp:", 130, 115);
      pdf.setFont("normal");
      pdf.setTextColor(80);
      pdf.text(
        item.timestamp ?? item.createdAt ?? "No Time Provided",
        130,
        122
      );

      // FOOTER BRANDING
      pdf.setFillColor(35, 35, 35);
      pdf.rect(0, 270, 210, 20, "F");
      pdf.setTextColor(255);
      pdf.setFontSize(10);
      pdf.text("Generated by Crescent App Dashboard • ", 45, 283);

      pdf.save(`Deposit-${item.transactionId ?? "Record"}.pdf`);
    } catch (err) {
      message.error("PDF Generation Failed ❌");
    }
  };

  const showModal = () => {
    setIsModalOpen(true);
  };
  const [payoutRequest] = usePayoutRequestMutation();
  const onFinish = (values: any) => {
    try {
      const data = {
        amount: Number(values.withdrawAmount),
        scheduledDate: values.payoutDate,
      };
      payoutRequest(data).unwrap();
      message.success("Payout Requested Successfully");
      setIsModalOpen(false);
      form.resetFields();
    } catch (error) {
      message.error("Payout Request Failed");
    }
  };

  const handleCancel = () => setIsModalOpen(false);

  return (
    <div className="">
      <div>
        <h1 className="text-3xl font-bold mb-4">Deposit</h1>
        <p className="text-lg text-gray-600 mb-4">
          See how your supporters are giving and where your impact is growing.
        </p>
      </div>
      <div className="bg-white border rounded-3xl p-6">
        <div className="flex justify-between items-center">
          <h1 className="text-lg font-medium">Total Deposits</h1>
          <div className="flex items-center gap-2 px-4 py-2 bg-gray-100 rounded-3xl text-sm text-gray-900 border hover:bg-blue-100">
            <img src={setting} alt="" />
            <button onClick={showModal}> Adjust Payout Schedule</button>
            {/* <DatePicker className=" " style={{ width: 50 }} /> */}
          </div>
        </div>
        <div className="flex justify-between items-center mt-12">
          <div className="flex justify-start items-end gap-1 mt-10 mb-6">
            <h1 className="text-3xl md:text-5xl font-bold">
              {" "}
              <span className="text-gray-400">$</span>
              {getMyBalance?.data?.availableBalance} /{" "}
              <span className="text-gray-400 text-2xl">{getMyBalance?.data?.pendingBalance}</span>
            </h1>
            {/* <p className="text-green-500">
              8.2% <span className="text-gray-400"> vs last month</span>
            </p> */}
          </div>
          <p className="px-4 py-2 bg-gray-100 rounded-3xl">
            Your next payout is in 3 days: 10th May, 2025
          </p>
        </div>
      </div>

      <div className="flex justify-between items-center mb-5 mt-8">
        <h1 className="text-xl md:text-2xl font-semibold">Deposit</h1>
        <Select
          value={payoutMethod}
          className="w-[150px]"
          onChange={(v) => setPayoutMethod(v)}
        >
          <Select.Option value="paypal">PayPal</Select.Option>
          <Select.Option value="credit_card">Credit Card</Select.Option>
          <Select.Option value="bank_transfer">Bank Transfer</Select.Option>
          <Select.Option value="stripe_connect">Stripe Connect</Select.Option>
        </Select>
      </div>

      {/* Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {depositData?.data.map((item: any) => (
          <div
            ref={printRef}
            key={item.key}
            className="bg-white p-6 rounded-xl shadow-sm border flex flex-col gap-4"
          >
            <div className="flex justify-between items-center gap-2 border-b pb-6">
              <h2 className="text-2xl font-semibold">
                {item.requestedAmount} {item?.currency}
              </h2>
              <div className="bg-purple-500 h-10 w-10 rounded-full flex justify-center items-center curesor-pointer">
                <HiOutlineArrowNarrowDown
                  onClick={() => handleDownLoadPdf(item)}
                  className="h-5 w-5 text-white cursor-pointer"
                />
              </div>
            </div>
            <h1 className="text-xl font-lg">Summery</h1>
            <div className="text-gray-600 space-y-2 text-sm">
              <div className="flex justify-between">
                <p>Deposited to</p>
                <p>{item.organization?.name}</p>
              </div>
              <div className="flex justify-between">
                <p>Stripe Connect Account Id</p>
                <p>
                  {item.organization?.stripeConnectAccountId
                    ? item.organization?.stripeConnectAccountId.slice(0, 3) +
                      "*".repeat(
                        item.organization?.stripeConnectAccountId.length - 7
                      ) +
                      item.organization?.stripeConnectAccountId.slice(-4)
                    : ""}
                </p>
              </div>
              <div className="flex justify-between">
                <p>Transfer via</p>
                <p>{item.payoutMethod}</p>
              </div>
              <div className="flex justify-between border-b pb-6">
                <p>Status</p>
                <span
                  className={`px-3 py-1 rounded-md text-white ${
                    item.status === "Successful"
                      ? "bg-green-500"
                      : item.status === "pending"
                      ? "bg-yellow-500"
                      : "bg-red-500"
                  }`}
                >
                  {item.status}
                </span>
              </div>
              <div className="flex justify-between pt-6">
                <p>Timestamp</p>
                <p>{item.createdAt}</p>
              </div>
              <div className="flex justify-between">
                <p>Payout Number </p>
                <p>{item.payoutNumber}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Pagination */}
      <div className="my-10 flex justify-end">
        <Pagination
          current={page}
          total={depositData?.meta?.total}
          pageSize={limit}
          onChange={(newPage) => setPage(newPage)}
        />
      </div>

      <Modal
        title="Adjust Payout Schedule"
        open={isModalOpen}
        onOk={() => form.submit()}
        onCancel={handleCancel}
      >
        <Form form={form} layout="vertical" onFinish={onFinish}>
          <Form.Item
            label="Select Payout Date"
            name="payoutDate"
            rules={[{ required: true, message: "Please select a payout date" }]}
          >
            <DatePicker style={{ width: "100%" }} />
          </Form.Item>

          <Form.Item label="Available Balance">
            <Input value={getMyBalance?.data?.lifetimeEarnings} disabled />
          </Form.Item>

          <Form.Item
            label="Amount to Withdraw"
            name="withdrawAmount"
            rules={[
              { required: true, message: "Enter withdrawal amount" },
              { pattern: /^\d+$/, message: "Amount must be a number" },
            ]}
          >
            <Input placeholder="Enter amount" />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default Deposits;
